default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ee_trading
  host: localhost
  username: jmarbach
  password: nakamoto

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>